Software quality practice 1: AlgoritmosGeneticos.hpp File Reference
AlgoritmosGeneticos.hpp File Reference
File with the declaration of some functions used by the class AlgoritmosGeneticos.
#include "Poblacion.hpp"
Functions
int geneticoGeneracional (int nIndividuos, int evaluaciones, Poblacion &entorno, double cruce, int tipo, double mutacion)
Generational genetic algorithm with elitism.
int geneticoEstacionario (int nIndividuos, int evaluaciones, Poblacion &entorno, int parejas, int tipo, double mutacion)
Steady one genetic algorithm.
Detailed Description
File with the declaration of some functions used by the class AlgoritmosGeneticos.
Definition in file AlgoritmosGeneticos.hpp.
Function Documentation
geneticoEstacionario()
int geneticoEstacionario (int nIndividuos, int evaluaciones, Poblacion & entorno, int parejas, int tipo, double mutacion)
Steady one genetic algorithm.
Parameters
[in] nIndividuos Number of individuals of the population that the algorithm will use
[in] evaluaciones Number of evaluations of the individuals
[in,out] entorno The individuals the algorithm will affect
[in] parejas Number of pairs that will be crossed
[in] tipo Cross type, 0 = BLX 1 = 2 Points
[in] mutacion Mutation probability
Returns
The minimum interference calculated is returned
Definition at line 66 of file AlgoritmosGeneticos.cpp.
References Poblacion::comprobarRepetidos(), Poblacion::evolucionEstacionaria(), Especimen::getInterference(), Poblacion::getMejor(), Poblacion::iniciarPoblacion(), and Poblacion::reinicializar().
Referenced by main().
geneticoGeneracional()
int geneticoGeneracional (int nIndividuos, int evaluaciones, Poblacion & entorno, double cruce, int tipo, double mutacion)
Generational genetic algorithm with elitism.
Parameters
[in] nIndividuos Number of individuals of the population that the algorithm will use
[in] evaluaciones Number of evaluations of the individuals
[in,out] entorno The individuals the algorithm will affect
[in] cruce Cross probability
[in] tipo Cross type, 0 = BLX 1 = 2 Points
[in] mutacion Mutation probability
Returns
The minimum interference calculated is returned
Definition at line 22 of file AlgoritmosGeneticos.cpp.
References Poblacion::comprobarRepetidos(), Poblacion::evolucionGeneracional(), Especimen::getInterference(), Poblacion::getMejor(), and Poblacion::reinicializar().
Referenced by am1001(), am1001Mej(), am1010(), and main().