Software quality practice 1: AlgoritmosGeneticos.cpp File Reference
AlgoritmosGeneticos.cpp File Reference
File with the main code of the AlgoritmosGeneticos class.
#include "AlgoritmosGeneticos.hpp"
Functions
int geneticoGeneracional (int nIndividuos, int evaluaciones, Poblacion &entorno, double cruce, int tipo, double mutacion)
Generational genetic algorithm with elitism.
int geneticoEstacionario (int nIndividuos, int evaluaciones, Poblacion &entorno, int parejas, int tipo, double mutacion)
Steady one genetic algorithm.
int busquedaLineal (Especimen &esp, int numEval)
Lineal search in an specific element of the population.
int am1010 (int nIndividuos, int evaluaciones, Poblacion &entorno, double cruce, int tipo, double mutacion)
Memetic algorithm, every 10 iterations the algorithm is applied to the whole population.
int am1001 (int nIndividuos, int evaluaciones, Poblacion &entorno, double cruce, int tipo, double mutacion)
Memetic algorithm, every 10 iterations the algorithm is applied to 10% of the population.
int am1001Mej (int nIndividuos, int evaluaciones, Poblacion &entorno, double cruce, int tipo, double mutacion)
Memetic algorithm, every 10 iterations the algorithm is applied to the 10% of the population with the best results.
Detailed Description
File with the main code of the AlgoritmosGeneticos class.
Definition in file AlgoritmosGeneticos.cpp.
Function Documentation
am1001()
int am1001 (int nIndividuos, int evaluaciones, Poblacion & entorno, double cruce, int tipo, double mutacion)
Memetic algorithm, every 10 iterations the algorithm is applied to 10% of the population.
Parameters
[in] nIndividuos Number of individuals of the population that the algorithm will use
[in] evaluaciones Number of evaluations of the individuals
[in,out] entorno The individuals the algorithm will affect
[in] cruce Cross probability
[in] tipo Cross type, 0 = BLX 1 = 2 Points
[in] mutacion Mutation probability
Returns
The minimum interference calculated is returned
Definition at line 180 of file AlgoritmosGeneticos.cpp.
References Poblacion::actualizarMejor(), busquedaLineal(), geneticoGeneracional(), Especimen::getInterference(), Poblacion::getMejor(), getRandomInt(), Poblacion::mundo_, and Poblacion::reinicializar().
Referenced by main().
am1001Mej()
int am1001Mej (int nIndividuos, int evaluaciones, Poblacion & entorno, double cruce, int tipo, double mutacion)
Memetic algorithm, every 10 iterations the algorithm is applied to the 10% of the population with the best results.
Parameters
[in] nIndividuos Number of individuals of the population that the algorithm will use
[in] evaluaciones Number of evaluations of the individuals
[in,out] entorno The individuals the algorithm will affect
[in] cruce Cross probability
[in] tipo Cross type, 0 = BLX 1 = 2 Points
[in] mutacion Mutation probability
Returns
The minimum interference calculated is returned
Definition at line 229 of file AlgoritmosGeneticos.cpp.
References Poblacion::actualizarMejor(), busquedaLineal(), geneticoGeneracional(), Especimen::getInterference(), Poblacion::getMejor(), Poblacion::mundo_, and Poblacion::reinicializar().
Referenced by main().
am1010()
int am1010 (int nIndividuos, int evaluaciones, Poblacion & entorno, double cruce, int tipo, double mutacion)
Memetic algorithm, every 10 iterations the algorithm is applied to the whole population.
Parameters
[in] nIndividuos Number of individuals of the population that the algorithm will use
[in] evaluaciones Number of evaluations of the individuals
[in,out] entorno The individuals the algorithm will affect
[in] cruce Cross probability
[in] tipo Cross type, 0 = BLX 1 = 2 Points
[in] mutacion Mutation probability
Returns
The minimum interference calculated is returned
Definition at line 134 of file AlgoritmosGeneticos.cpp.
References Poblacion::actualizarMejor(), busquedaLineal(), geneticoGeneracional(), Especimen::getInterference(), Poblacion::getMejor(), Poblacion::mundo_, and Poblacion::reinicializar().
Referenced by main().
busquedaLineal()
int busquedaLineal (Especimen & esp, int numEval)
Lineal search in an specific element of the population.
Parameters
[in,out] esp The element in which the lineal search will be used
[in] numEval Number of iterations made in the search
Returns
The minimum interference calculated through the lineal search is returned.
Definition at line 96 of file AlgoritmosGeneticos.cpp.
References Especimen::evaluate(), Especimen::getFreqRange(), Especimen::getInterference(), getRandomInt(), Especimen::getSize(), Especimen::scanVal(), and Especimen::sigVal().
Referenced by am1001(), am1001Mej(), and am1010().
geneticoEstacionario()
int geneticoEstacionario (int nIndividuos, int evaluaciones, Poblacion & entorno, int parejas, int tipo, double mutacion)
Steady one genetic algorithm.
Parameters
[in] nIndividuos Number of individuals of the population that the algorithm will use
[in] evaluaciones Number of evaluations of the individuals
[in,out] entorno The individuals the algorithm will affect
[in] parejas Number of pairs that will be crossed
[in] tipo Cross type, 0 = BLX 1 = 2 Points
[in] mutacion Mutation probability
Returns
The minimum interference calculated is returned
Definition at line 66 of file AlgoritmosGeneticos.cpp.
References Poblacion::comprobarRepetidos(), Poblacion::evolucionEstacionaria(), Especimen::getInterference(), Poblacion::getMejor(), Poblacion::iniciarPoblacion(), and Poblacion::reinicializar().
Referenced by main().
geneticoGeneracional()
int geneticoGeneracional (int nIndividuos, int evaluaciones, Poblacion & entorno, double cruce, int tipo, double mutacion)
Generational genetic algorithm with elitism.
Parameters
[in] nIndividuos Number of individuals of the population that the algorithm will use
[in] evaluaciones Number of evaluations of the individuals
[in,out] entorno The individuals the algorithm will affect
[in] cruce Cross probability
[in] tipo Cross type, 0 = BLX 1 = 2 Points
[in] mutacion Mutation probability
Returns
The minimum interference calculated is returned
Definition at line 22 of file AlgoritmosGeneticos.cpp.
References Poblacion::comprobarRepetidos(), Poblacion::evolucionGeneracional(), Especimen::getInterference(), Poblacion::getMejor(), and Poblacion::reinicializar().
Referenced by am1001(), am1001Mej(), am1010(), and main().