Software quality practice 1: Especimen.cpp File Reference
Especimen.cpp File Reference
File of the class Especimen with the code of the functions.
#include "Especimen.hpp"
Functions
void cruce2Puntos (Especimen &padreA, Especimen &padreB, int minimo, int maximo)
Cross in two points algorithm, exchanges the fragments of the two vectors delimited by the points minimo and maximo.
void cruceBlx (Especimen &padreA, Especimen &padreB, float alpha)
BLX cross algorithm, changes the frequency of the individuals by an intermediate value obtained by their current values and a randomness factor.
void mutar (Especimen &individuo, double probabilidad)
Mutates the frequencies of an individual randomly.
Detailed Description
File of the class Especimen with the code of the functions.
Definition in file Especimen.cpp.
Function Documentation
cruce2Puntos()
void cruce2Puntos (Especimen & padreA, Especimen & padreB, int minimo = 1, int maximo = 0)
Cross in two points algorithm, exchanges the fragments of the two vectors delimited by the points minimo and maximo.
Parameters
[in,out] padreA first vector that will be used for the cross
[in,out] padreB second vector that will be used for the cross
[in] minimo first point of the cross
[in] maximo second point of the cross
Definition at line 416 of file Especimen.cpp.
References Especimen::freqs_, getRandomInt(), and Especimen::indexes_.
Referenced by Poblacion::evolucionEstacionaria(), and Poblacion::evolucionGeneracional().
cruceBlx()
void cruceBlx (Especimen & padreA, Especimen & padreB, float alpha = 0.1)
BLX cross algorithm, changes the frequency of the individuals by an intermediate value obtained by their current values and a randomness factor.
Parameters
[in,out] padreA first vector that will be used for the cross
[in,out] padreB second vector that will be used for the cross
[in] alpha percentage of randomness, 0.5 is the standard
Definition at line 446 of file Especimen.cpp.
References Especimen::freqs_, getRandomInt(), Especimen::indexes_, and Especimen::transistors_.
Referenced by Poblacion::evolucionEstacionaria(), and Poblacion::evolucionGeneracional().
mutar()
void mutar (Especimen & individuo, double probabilidad = 0.1)
Mutates the frequencies of an individual randomly.
Parameters
[in,out] individuo individual that will be muted
[in] probabilidad mutation probablility, the standard is 0.1
Definition at line 483 of file Especimen.cpp.
References Especimen::freqs_, getRandomInt(), Especimen::indexes_, and Especimen::transistors_.
Referenced by Poblacion::evolucionEstacionaria(), and Poblacion::evolucionGeneracional().