Software quality practice 1: Random.hpp File Reference
Random.hpp File Reference
headers files for random function
#include <iostream>
#include <stdlib.h>
#include <climits>
Functions
int getRandomInt (int inferior, int superior)
Generates an integer within a range between two numbers(int) being both included.
Detailed Description
headers files for random function
Author
sobremesa Created on 12 November 2017, 12:34
Definition in file Random.hpp.
Function Documentation
getRandomInt()
int getRandomInt (int inferior, int superior)
Generates an integer within a range between two numbers(int) being both included.
Parameters
[in] inferior Lower bound (closed interval)
[in] superior Upper bound (closed interval)
Returns
Random integer within the interval
Definition at line 16 of file Random.cpp.
Referenced by am1001(), busquedaLineal(), cruce2Puntos(), cruceBlx(), Poblacion::evolucionEstacionaria(), Poblacion::evolucionGeneracional(), Especimen::fullGreedInit(), Transistor::getRandFrec(), Especimen::greedInit(), and mutar().