Software quality practice 1: Random.cpp File Reference
Random.cpp File Reference
Sources for random function.
#include "Random.hpp"
Functions
int getRandomInt (int inferior, int superior)
Generates an integer within a range between two numbers(int) being both included.
Detailed Description
Sources for random function.
Definition in file Random.cpp.
Function Documentation
getRandomInt()
int getRandomInt (int inferior, int superior)
Generates an integer within a range between two numbers(int) being both included.
Parameters
[in] inferior Lower bound (closed interval)
[in] superior Upper bound (closed interval)
Returns
Random integer within the interval
Definition at line 16 of file Random.cpp.
Referenced by am1001(), busquedaLineal(), cruce2Puntos(), cruceBlx(), Poblacion::evolucionEstacionaria(), Poblacion::evolucionGeneracional(), Especimen::fullGreedInit(), Transistor::getRandFrec(), Especimen::greedInit(), and mutar().