Software quality practice 1: Poblacion Class Reference
Poblacion Class Reference
Class Poblacion, managing a set of individuals.
#include <Poblacion.hpp>
Public Member Functions
Poblacion (std::vector< Transistor > *transistors, std::vector< Restriction > *restrictions, std::vector< unsigned > *indxTransRestr)
Default Constructor.
Poblacion (const Poblacion &orig)
Copy Constructor.
void iniciarPoblacion (int nIndividuos)
Generates and establish the individuals of a population by a greedy algorithm.
void evolucionEstacionaria (int tipoCruce, double pMutacion=0.1, int parejas=1)
Evolves population using a steady one model.
void evolucionGeneracional (double probabilidad, int tipoCruce, double pMutacion=0.1)
Evolves population using a generational model.
bool comprobarRepetidos ()
Check if the population has at least a 20% of different individuals.
void actualizarMejor ()
Updates the best candidate of the population.
void reinicializar ()
Reinit population preserving the best previous individual.
Especimen getMejor ()
Gets the best individual of the population.
virtual ~Poblacion ()
Destroyer.
Private Attributes
std::vector< Transistor > * transistors_
Vector with the transistors of the individual.
std::vector< Restriction > * restrictions_
Vector with the restrictions that the individual will have to consider.
std::vector< unsigned > * indxTransRestr_
Indexes of the restrictions that we will have to be taken into account.
std::vector< Especimen > * mundo_
Vector with the individuals of the population.
int mejor_
Index to keep track of the best individual.
Friends
int am1010 (int nIndividuos, int evaluaciones, Poblacion &entorno, double cruce, int tipo, double mutacion)
Memetic algorithm, every 10 iterations the algorithm is applied to the whole population.
int am1001 (int nIndividuos, int evaluaciones, Poblacion &entorno, double cruce, int tipo, double mutacion)
Memetic algorithm, every 10 iterations the algorithm is applied to 10% of the population.
int am1001Mej (int nIndividuos, int evaluaciones, Poblacion &entorno, double cruce, int tipo, double mutacion)
Memetic algorithm, every 10 iterations the algorithm is applied to the 10% of the population with the best results.
Detailed Description
Class Poblacion, managing a set of individuals.
Definition at line 25 of file Poblacion.hpp.
Constructor & Destructor Documentation
Poblacion() [1/2]
Poblacion::Poblacion (std::vector< Transistor > * transistors, std::vector< Restriction > * restrictions, std::vector< unsigned > * indxTransRestr)
Default Constructor.
Generates a new population
Parameters
[in] transistors vector with the transistors that conform the population
[in] restrictions vector with the restrictions that rules the ppopulation
[in] indxTransRestr Indice que indica la posición de cada transistor en el conjunto de restricciones
Definition at line 21 of file Poblacion.cpp.
References mejor_, and mundo_.
Poblacion() [2/2]
Poblacion::Poblacion (const Poblacion & orig)
Copy Constructor.
Generates a new copy of a given population
Parameters
[in] orig Original population to copy
Definition at line 38 of file Poblacion.cpp.
References mundo_.
~Poblacion()
Poblacion::~Poblacion () virtual
Destroyer.
Free allocated memory when the object is destroyed
Definition at line 53 of file Poblacion.cpp.
References mundo_.
Member Function Documentation
actualizarMejor()
void Poblacion::actualizarMejor ()
Updates the best candidate of the population.
Definition at line 312 of file Poblacion.cpp.
References mejor_, and mundo_.
Referenced by am1001(), am1001Mej(), am1010(), and iniciarPoblacion().
comprobarRepetidos()
bool Poblacion::comprobarRepetidos ()
Check if the population has at least a 20% of different individuals.
Returns
boolean
Definition at line 254 of file Poblacion.cpp.
References mundo_.
Referenced by geneticoEstacionario(), and geneticoGeneracional().
evolucionEstacionaria()
void Poblacion::evolucionEstacionaria (int tipoCruce, double pMutacion = 0.1, int parejas = 1)
Evolves population using a steady one model.
Parameters
[in] tipoCruce Cross type to use, 0 = BLX 1 = 2 Points
[in] pMutacion Mutation probability
[in] parejas Numbers of pairs to cross
Definition at line 192 of file Poblacion.cpp.
References cruce2Puntos(), cruceBlx(), getRandomInt(), mejor_, mundo_, and mutar().
Referenced by geneticoEstacionario().
evolucionGeneracional()
void Poblacion::evolucionGeneracional (double probabilidad, int tipoCruce, double pMutacion = 0.1)
Evolves population using a generational model.
Parameters
[in] probabilidad Cross probability
[in] tipoCruce Cross type to use, 0 = BLX 1 = 2 Points
[in] pMutacion Mutation probability
Definition at line 85 of file Poblacion.cpp.
References cruce2Puntos(), cruceBlx(), getRandomInt(), mejor_, mundo_, and mutar().
Referenced by geneticoGeneracional().
getMejor()
Especimen Poblacion::getMejor ()
Gets the best individual of the population.
Returns
Especimen
Definition at line 301 of file Poblacion.cpp.
References mejor_, and mundo_.
Referenced by am1001(), am1001Mej(), am1010(), geneticoEstacionario(), geneticoGeneracional(), and main().
iniciarPoblacion()
void Poblacion::iniciarPoblacion (int nIndividuos)
Generates and establish the individuals of a population by a greedy algorithm.
Parameters
[in] nIndividuos number of individuals at the population
Definition at line 65 of file Poblacion.cpp.
References actualizarMejor(), indxTransRestr_, mundo_, restrictions_, and transistors_.
Referenced by geneticoEstacionario(), and main().
reinicializar()
void Poblacion::reinicializar ()
Reinit population preserving the best previous individual.
Definition at line 272 of file Poblacion.cpp.
References Especimen::getInterference(), indxTransRestr_, mejor_, mundo_, restrictions_, and transistors_.
Referenced by am1001(), am1001Mej(), am1010(), geneticoEstacionario(), and geneticoGeneracional().
Friends And Related Function Documentation
am1001
int am1001 (int nIndividuos, int evaluaciones, Poblacion & entorno, double cruce, int tipo, double mutacion) friend
Memetic algorithm, every 10 iterations the algorithm is applied to 10% of the population.
Parameters
[in] nIndividuos Number of individuals of the population that the algorithm will use
[in] evaluaciones Number of evaluations of the individuals
[in,out] entorno The individuals the algorithm will affect
[in] cruce Cross probability
[in] tipo Cross type, 0 = BLX 1 = 2 Points
[in] mutacion Mutation probability
Returns
The minimum interference calculated is returned
Definition at line 180 of file AlgoritmosGeneticos.cpp.
am1001Mej
int am1001Mej (int nIndividuos, int evaluaciones, Poblacion & entorno, double cruce, int tipo, double mutacion) friend
Memetic algorithm, every 10 iterations the algorithm is applied to the 10% of the population with the best results.
Parameters
[in] nIndividuos Number of individuals of the population that the algorithm will use
[in] evaluaciones Number of evaluations of the individuals
[in,out] entorno The individuals the algorithm will affect
[in] cruce Cross probability
[in] tipo Cross type, 0 = BLX 1 = 2 Points
[in] mutacion Mutation probability
Returns
The minimum interference calculated is returned
Definition at line 229 of file AlgoritmosGeneticos.cpp.
am1010
int am1010 (int nIndividuos, int evaluaciones, Poblacion & entorno, double cruce, int tipo, double mutacion) friend
Memetic algorithm, every 10 iterations the algorithm is applied to the whole population.
Parameters
[in] nIndividuos Number of individuals of the population that the algorithm will use
[in] evaluaciones Number of evaluations of the individuals
[in,out] entorno The individuals the algorithm will affect
[in] cruce Cross probability
[in] tipo Cross type, 0 = BLX 1 = 2 Points
[in] mutacion Mutation probability
Returns
The minimum interference calculated is returned
Definition at line 134 of file AlgoritmosGeneticos.cpp.
Member Data Documentation
indxTransRestr_
std::vector<unsigned>* Poblacion::indxTransRestr_ private
Indexes of the restrictions that we will have to be taken into account.
Definition at line 59 of file Poblacion.hpp.
Referenced by iniciarPoblacion(), and reinicializar().
mejor_
int Poblacion::mejor_ private
Index to keep track of the best individual.
Definition at line 63 of file Poblacion.hpp.
Referenced by actualizarMejor(), evolucionEstacionaria(), evolucionGeneracional(), getMejor(), Poblacion(), and reinicializar().
mundo_
std::vector<Especimen>* Poblacion::mundo_ private
Vector with the individuals of the population.
Definition at line 61 of file Poblacion.hpp.
Referenced by actualizarMejor(), am1001(), am1001Mej(), am1010(), comprobarRepetidos(), evolucionEstacionaria(), evolucionGeneracional(), getMejor(), iniciarPoblacion(), Poblacion(), reinicializar(), and ~Poblacion().
restrictions_
std::vector<Restriction>* Poblacion::restrictions_ private
Vector with the restrictions that the individual will have to consider.
Definition at line 58 of file Poblacion.hpp.
Referenced by iniciarPoblacion(), and reinicializar().
transistors_
std::vector<Transistor>* Poblacion::transistors_ private
Vector with the transistors of the individual.
Definition at line 57 of file Poblacion.hpp.
Referenced by iniciarPoblacion(), and reinicializar().
The documentation for this class was generated from the following files:
Poblacion.hpp
Poblacion.cpp