Software quality practice 1: Parser Class Reference
Parser Class Reference
Class Parser, with the objective of translating the information stored in the different .txt files regarding the problem to the different data structures used in the program.
#include <Parser.hpp>
Static Public Member Functions
static void FRangeParse (std::string path, std::vector< std::vector< int >> &results)
Generates a matrix with the different levels of frequencies given by "dom.txt".
static void RTParse (std::string path, std::vector< Restriction > &restrictions, std::vector< int > &equivalenceIndex)
Generates a list of transistors given by the file "ctr.txt".
static int TParse (std::string path, std::vector< std::vector< int >> *frecs, std::vector< Transistor > &result, std::vector< int > &equivalenceIndex, int TNumber=INT_MAX)
Generates a vector with the transistors given by "var.txt".
static void genIndexTransRestr (std::vector< Transistor > &transistors, std::vector< Restriction > &restrictions, std::vector< unsigned > &result)
Calculates indexes of the restrictions that we will have to be taken into account.
Detailed Description
Class Parser, with the objective of translating the information stored in the different .txt files regarding the problem to the different data structures used in the program.
Definition at line 22 of file Parser.hpp.
Member Function Documentation
FRangeParse()
void Parser::FRangeParse (std::string path, std::vector< std::vector< int >> & results) static
Generates a matrix with the different levels of frequencies given by "dom.txt".
Parameters
[in] path path in which the file is stored
[in,out] results data structure in which the results will be stored
Definition at line 16 of file Parser.cpp.
Referenced by main().
genIndexTransRestr()
void Parser::genIndexTransRestr (std::vector< Transistor > & transistors_, std::vector< Restriction > & restrictions_, std::vector< unsigned > & result) static
Calculates indexes of the restrictions that we will have to be taken into account.
Parameters
[in,out] transistors_ vector with the transistors
[in,out] restrictions_ vector with the restrictions
[in,out] result Indexes of the restrictions that we will have to be taken into account
Definition at line 154 of file Parser.cpp.
Referenced by main().
RTParse()
void Parser::RTParse (std::string path, std::vector< Restriction > & restrictions, std::vector< int > & equivalenceIndex) static
Generates a list of transistors given by the file "ctr.txt".
Parameters
[in] path path in which the file is stored
[in,out] restrictions data structure in which the restrictions will be stored
[in,out] equivalenceIndex refactoring index to avoid gaps between transistors
Returns
The number of transistors returned.
Definition at line 106 of file Parser.cpp.
References Restriction::bound, Restriction::interference, Restriction::trans1, and Restriction::trans2.
Referenced by main().
TParse()
int Parser::TParse (std::string path, std::vector< std::vector< int >> * frecs, std::vector< Transistor > & result, std::vector< int > & equivalenceIndex, int TNumber = INT_MAX) static
Generates a vector with the transistors given by "var.txt".
Parameters
[in] path path in which the file is stored
[in] frecs data structure in which the frequencies range of each transistor will be stored
[in,out] result data structure in which the results will be stored
[in,out] equivalenceIndex refactoring index to avoid gaps between transistors
[in,out] TNumber the total number of transistors of the file
Returns
The total number of transistors generated
Definition at line 57 of file Parser.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
Parser.hpp
Parser.cpp