Software quality practice 1: Transistor Class Reference
Transistor Class Reference
The class Transistor encapsulates all the information related to transmisors, and the frequencies it manages.
#include <Transistor.hpp>
Public Member Functions
Transistor (unsigned numID, int NRange, std::vector< std::vector< int >> *frecs)
Transistor default constructor.
int getNRange ()
Gets the range of transistor's frequencies in the frequencies matrix.
int getRandFrec ()
Gets a random frequency inside his set of frequencies.
int getFreqRange ()
Gets the number of different frequencies a transistor has.
int getNumID ()
Gets the ID number of the transistor.
void setFrecs (std::vector< std::vector< int >> *frecs)
Set the frequencies matrix.
int operator[] (unsigned indx)
Access the frequence of a transistor.
virtual ~Transistor ()
Destroyer.
Private Attributes
unsigned numID_
Transistor id.
int NRange_
Range Number id in the frequencies matrix.
std::vector< std::vector< int > > * frecs_
Reference to Frequencies matrix.
Detailed Description
The class Transistor encapsulates all the information related to transmisors, and the frequencies it manages.
Definition at line 18 of file Transistor.hpp.
Constructor & Destructor Documentation
Transistor()
Transistor::Transistor (unsigned numID, int NRange, std::vector< std::vector< int >> * frecs)
Transistor default constructor.
Parameters
[in] numID Transistor unique ID
[in] NRange Range of frequencies in the Frequencies matrix
[in] frecs Reference to Frequencies matrix
Definition at line 17 of file Transistor.cpp.
References frecs_, NRange_, and numID_.
~Transistor()
Transistor::~Transistor () virtual
Destroyer.
Free allocated memory when the object is destroyed
Definition at line 104 of file Transistor.cpp.
Member Function Documentation
getFreqRange()
int Transistor::getFreqRange ()
Gets the number of different frequencies a transistor has.
Returns
The range of frequencies available for the transistor
Definition at line 92 of file Transistor.cpp.
References frecs_, and NRange_.
Referenced by getRandFrec(), and operator[]().
getNRange()
int Transistor::getNRange ()
Gets the range of transistor's frequencies in the frequencies matrix.
Returns
Range number
Definition at line 31 of file Transistor.cpp.
References NRange_.
getNumID()
int Transistor::getNumID ()
Gets the ID number of the transistor.
Returns
Transistor ID
Definition at line 80 of file Transistor.cpp.
References numID_.
getRandFrec()
int Transistor::getRandFrec ()
Gets a random frequency inside his set of frequencies.
Returns
Random frequencies within his range of frequencies inside the frequencies matrix.
Definition at line 42 of file Transistor.cpp.
References getFreqRange(), and getRandomInt().
operator[]()
int Transistor::operator[] (unsigned indx)
Access the frequence of a transistor.
Parameters
[in] indx Position of the frequency
Returns
Frequency of the transistor that is in the given position
Definition at line 68 of file Transistor.cpp.
References frecs_, getFreqRange(), and NRange_.
setFrecs()
void Transistor::setFrecs (std::vector< std::vector< int >> * frecs)
Set the frequencies matrix.
Parameters
frecs Reference to frequencies matrix
Definition at line 55 of file Transistor.cpp.
References frecs_.
Member Data Documentation
frecs_
std::vector<std::vector<int> >* Transistor::frecs_ private
Reference to Frequencies matrix.
Definition at line 22 of file Transistor.hpp.
Referenced by getFreqRange(), operator[](), setFrecs(), and Transistor().
NRange_
int Transistor::NRange_ private
Range Number id in the frequencies matrix.
Definition at line 21 of file Transistor.hpp.
Referenced by getFreqRange(), getNRange(), operator[](), and Transistor().
numID_
unsigned Transistor::numID_ private
Transistor id.
Definition at line 20 of file Transistor.hpp.
Referenced by getNumID(), and Transistor().
The documentation for this class was generated from the following files:
Transistor.hpp
Transistor.cpp