Software quality practice 1: Especimen Class Reference
Especimen Class Reference
Class Especimen, representing each member of the population.
#include <Especimen.hpp>
Public Member Functions
Especimen (std::vector< Transistor > *transistors, std::vector< Restriction > *restrictions, std::vector< unsigned > *indxTransRestr)
Main constructor.
Especimen (const Especimen &orig)
Copy constructor.
virtual ~Especimen ()
Destroyer.
int getSize ()
Getter of the size of the data structure in which the transistors of the individual are stored.
int getFreqRange (int trans)
Getter of the frequencies range.
int evaluate ()
Calculates the total sum of the interferences of the frequencies.
int scanVal (unsigned trans, int pos)
Calculates the interference that would result as a change in a frequency.
void sigVal (unsigned trans, int pos)
Increases the values of the frequency of the selected transistor.
bool operator== (const Especimen &otro)
Compares two instances of "Especimen. First the total sum of interference is compared, in case it is equal, the frequence values of the transistors are compared.
bool operator!= (const Especimen &otro)
Compares two instances of "Especimen. First the total sum of interference is compared, in case it is equal, the frequence values of the transistors are compared.
bool operator< (const Especimen &otro) const
Compares two instances of "Especimen. First the total sum of interference is compared, in case it is equal, the frequence values of the transistors are compared.
int getInterference () const
Getter of the totalInterference attribute.
Private Member Functions
void greedInit ()
Greedy initializer algorithm.
void randInit ()
Random initializer algorithm.
void fullGreedInit ()
Improved version of the greedy initializer algorithm.
int bestFreq (unsigned trans)
Searches the best frequency taking into account the restrictions of the transistors placed on his right in the data structure.
int calcCost (unsigned trans, int freq)
Calculates the individual cost of a transistor taking into account the restrictions related to the transistors placed on his right in the data structure.
int fullBestFreq (unsigned trans, unsigned cabecera, unsigned cola)
Calculates the best frequency of a transistor.
int fullCalcCost (unsigned trans, int freq, unsigned cabecera, unsigned cola)
Calculates the cost that a transistor adds to the total.
Private Attributes
std::vector< Transistor > * transistors_
Vector with the transistors of the individual.
std::vector< Restriction > * restrictions_
Vector with the restrictions that the individual will have to consider.
std::vector< int > freqs_
Vector with the frequencies of the individual.
std::vector< int > indexes_
Index which represents the valid frequencies this individual will be able to take.
std::vector< unsigned > * indxTransRestr_
Indexes of the restrictions that we will have to be taken into account.
int totalInterference_
The sum of the interference obtained for this member of the population.
Friends
void cruce2Puntos (Especimen &padreA, Especimen &padreB, int minimo=1, int maximo=0)
Cross in two points algorithm, exchanges the fragments of the two vectors delimited by the points minimo and maximo.
void cruceBlx (Especimen &padreA, Especimen &padreB, float alpha=0.1)
BLX cross algorithm, changes the frequency of the individuals by an intermediate value obtained by their current values and a randomness factor.
void mutar (Especimen &individuo, double probabilidad=0.1)
Mutates the frequencies of an individual randomly.
Detailed Description
Class Especimen, representing each member of the population.
Definition at line 21 of file Especimen.hpp.
Constructor & Destructor Documentation
Especimen() [1/2]
Especimen::Especimen (std::vector< Transistor > * transistors, std::vector< Restriction > * restrictions, std::vector< unsigned > * indxTransRestr)
Main constructor.
Generates an "Especimen" starting the frequences with a greedy algorithm
Parameters
[in] transistors Transistor vector in which the population will be stored
[in] restrictions Restrictions of the population
[in] indxTransRestr Index with the information of each transistor in the restriction group
Definition at line 19 of file Especimen.cpp.
References evaluate(), and randInit().
Especimen() [2/2]
Especimen::Especimen (const Especimen & orig)
Copy constructor.
Generates a copy of the "Especimen"
Parameters
[in] orig instance of the class Especimen
Definition at line 36 of file Especimen.cpp.
~Especimen()
Especimen::~Especimen () virtual
Destroyer.
Free allocated memory when the object is destroyed
Definition at line 401 of file Especimen.cpp.
Member Function Documentation
bestFreq()
int Especimen::bestFreq (unsigned trans) private
Searches the best frequency taking into account the restrictions of the transistors placed on his right in the data structure.
Parameters
[in] trans current transistor index
Returns
the minimum frequency found
Definition at line 273 of file Especimen.cpp.
References calcCost().
Referenced by greedInit().
calcCost()
int Especimen::calcCost (unsigned trans, int freq) private
Calculates the individual cost of a transistor taking into account the restrictions related to the transistors placed on his right in the data structure.
Parameters
[in] trans current transistor index
[in] freq current frequency index
Returns
the cost of the transistor
Definition at line 301 of file Especimen.cpp.
References freqs_, indxTransRestr_, restrictions_, and transistors_.
Referenced by bestFreq().
evaluate()
int Especimen::evaluate ()
Calculates the total sum of the interferences of the frequencies.
Returns
sum of the interferences
Definition at line 49 of file Especimen.cpp.
References freqs_, restrictions_, and totalInterference_.
Referenced by busquedaLineal(), and Especimen().
fullBestFreq()
int Especimen::fullBestFreq (unsigned trans, unsigned cabecera, unsigned cola) private
Calculates the best frequency of a transistor.
Parameters
[in] trans transistor for which the best frequency will be calculated
[in] cabecera beginning of the data structure in which the frequencies are stored
[in] cola end of the data structure in which the frequencies are stored
Returns
the frequency that adds the minimum value(best value) to the total sum of the interferences
Definition at line 180 of file Especimen.cpp.
References fullCalcCost().
Referenced by fullGreedInit().
fullCalcCost()
int Especimen::fullCalcCost (unsigned trans, int freq, unsigned cabecera, unsigned cola) private
Calculates the cost that a transistor adds to the total.
Parameters
[in] trans current transistor index
[in] freq current frequency index
[in] cabecera beginning of the data structure in which the frequencies are stored
[in] cola end of the data structure in which the frequencies are stored
Returns
the cost the transistor adds
Definition at line 209 of file Especimen.cpp.
References freqs_, restrictions_, and transistors_.
Referenced by fullBestFreq(), scanVal(), and sigVal().
fullGreedInit()
void Especimen::fullGreedInit () private
Improved version of the greedy initializer algorithm.
Definition at line 149 of file Especimen.cpp.
References freqs_, fullBestFreq(), getRandomInt(), indexes_, and transistors_.
getFreqRange()
int Especimen::getFreqRange (int trans)
Getter of the frequencies range.
Parameters
[in] trans transistor from which its frequencies range will be obtained
Returns
the frequency range
Definition at line 513 of file Especimen.cpp.
References transistors_.
Referenced by busquedaLineal().
getInterference()
int Especimen::getInterference () const
Getter of the totalInterference attribute.
Returns
the total interference
Definition at line 390 of file Especimen.cpp.
References totalInterference_.
Referenced by am1001(), am1001Mej(), am1010(), busquedaLineal(), geneticoEstacionario(), geneticoGeneracional(), main(), and Poblacion::reinicializar().
getSize()
int Especimen::getSize ()
Getter of the size of the data structure in which the transistors of the individual are stored.
Returns
the size of said data structure
Definition at line 525 of file Especimen.cpp.
References transistors_.
Referenced by busquedaLineal().
greedInit()
void Especimen::greedInit () private
Greedy initializer algorithm.
Definition at line 119 of file Especimen.cpp.
References bestFreq(), freqs_, getRandomInt(), indexes_, and transistors_.
operator!=()
bool Especimen::operator!= (const Especimen & otro)
Compares two instances of "Especimen. First the total sum of interference is compared, in case it is equal, the frequence values of the transistors are compared.
Parameters
[in] otro instance of the class Especimen
Returns
true if they are not equal, false if they are.
Definition at line 349 of file Especimen.cpp.
References freqs_, and totalInterference_.
operator<()
bool Especimen::operator< (const Especimen & otro) const
Compares two instances of "Especimen. First the total sum of interference is compared, in case it is equal, the frequence values of the transistors are compared.
Parameters
[in] otro instance of the class Especimen
Returns
false if otro has a smaller totalinterference value, true in the opposite case.
Definition at line 371 of file Especimen.cpp.
References freqs_, and totalInterference_.
operator==()
bool Especimen::operator== (const Especimen & otro)
Compares two instances of "Especimen. First the total sum of interference is compared, in case it is equal, the frequence values of the transistors are compared.
Parameters
[in] otro instance of the class Especimen
Returns
false if they are not equal, true if they are.
Definition at line 328 of file Especimen.cpp.
References freqs_, and totalInterference_.
randInit()
void Especimen::randInit () private
Random initializer algorithm.
Definition at line 102 of file Especimen.cpp.
References freqs_, indexes_, and transistors_.
Referenced by Especimen().
scanVal()
int Especimen::scanVal (unsigned trans, int pos)
Calculates the interference that would result as a change in a frequency.
Parameters
[in] trans transistor in which the frequency will change
[in] pos position of the frequency
Definition at line 66 of file Especimen.cpp.
References freqs_, fullCalcCost(), indexes_, totalInterference_, and transistors_.
Referenced by busquedaLineal().
sigVal()
void Especimen::sigVal (unsigned trans, int pos)
Increases the values of the frequency of the selected transistor.
Parameters
[in] trans transistor in which the frequency will change
[in] pos position of the frequency
Definition at line 88 of file Especimen.cpp.
References freqs_, fullCalcCost(), indexes_, totalInterference_, and transistors_.
Referenced by busquedaLineal().
Friends And Related Function Documentation
cruce2Puntos
void cruce2Puntos (Especimen & padreA, Especimen & padreB, int minimo = 1, int maximo = 0) friend
Cross in two points algorithm, exchanges the fragments of the two vectors delimited by the points minimo and maximo.
Parameters
[in,out] padreA first vector that will be used for the cross
[in,out] padreB second vector that will be used for the cross
[in] minimo first point of the cross
[in] maximo second point of the cross
Definition at line 416 of file Especimen.cpp.
cruceBlx
void cruceBlx (Especimen & padreA, Especimen & padreB, float alpha = 0.1) friend
BLX cross algorithm, changes the frequency of the individuals by an intermediate value obtained by their current values and a randomness factor.
Parameters
[in,out] padreA first vector that will be used for the cross
[in,out] padreB second vector that will be used for the cross
[in] alpha percentage of randomness, 0.5 is the standard
Definition at line 446 of file Especimen.cpp.
mutar
void mutar (Especimen & individuo, double probabilidad = 0.1) friend
Mutates the frequencies of an individual randomly.
Parameters
[in,out] individuo individual that will be muted
[in] probabilidad mutation probablility, the standard is 0.1
Definition at line 483 of file Especimen.cpp.
Member Data Documentation
freqs_
std::vector<int> Especimen::freqs_ private
Vector with the frequencies of the individual.
Definition at line 51 of file Especimen.hpp.
Referenced by calcCost(), cruce2Puntos(), cruceBlx(), evaluate(), fullCalcCost(), fullGreedInit(), greedInit(), mutar(), operator!=(), operator<(), operator==(), randInit(), scanVal(), and sigVal().
indexes_
std::vector<int> Especimen::indexes_ private
Index which represents the valid frequencies this individual will be able to take.
Definition at line 52 of file Especimen.hpp.
Referenced by cruce2Puntos(), cruceBlx(), fullGreedInit(), greedInit(), mutar(), randInit(), scanVal(), and sigVal().
indxTransRestr_
std::vector<unsigned>* Especimen::indxTransRestr_ private
Indexes of the restrictions that we will have to be taken into account.
Definition at line 53 of file Especimen.hpp.
Referenced by calcCost().
restrictions_
std::vector<Restriction>* Especimen::restrictions_ private
Vector with the restrictions that the individual will have to consider.
Definition at line 48 of file Especimen.hpp.
Referenced by calcCost(), evaluate(), and fullCalcCost().
totalInterference_
int Especimen::totalInterference_ private
The sum of the interference obtained for this member of the population.
Definition at line 65 of file Especimen.hpp.
Referenced by evaluate(), getInterference(), operator!=(), operator<(), operator==(), scanVal(), and sigVal().
transistors_
std::vector<Transistor>* Especimen::transistors_ private
Vector with the transistors of the individual.
Definition at line 47 of file Especimen.hpp.
Referenced by calcCost(), cruceBlx(), fullCalcCost(), fullGreedInit(), getFreqRange(), getSize(), greedInit(), mutar(), randInit(), scanVal(), and sigVal().
The documentation for this class was generated from the following files:
Especimen.hpp
Especimen.cpp